#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/common-functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

cmd-agent-api-destroy() {
  declare desc="destroy Agent API service"
  local cmd="agent:api-destroy"
  [[ "$1" == "$cmd" ]] && shift 1
  declare SERVICE="$1"
  declare FORCE="$2"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a service name"
  verify_service_name "$SERVICE"

  if [[ "$FORCE" != "-f" ]] && [[ "$FORCE" != "--force" ]]; then
    dokku_log_warn "WARNING: This will destroy Agent API service $SERVICE and its session data."
    dokku_log_warn "To proceed, type \"$SERVICE\""
    echo ""
    read -rp "> " input
    if [[ "$input" != "$SERVICE" ]]; then
      dokku_log_warn "Confirmation did not match. Aborted."
      exit 1
    fi
  fi

  service_destroy "$SERVICE"
}

cmd-agent-api-destroy "$@"
