#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/common-functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

cmd-agent-api-set-config() {
  declare desc="update agent.yaml config for a service"
  local cmd="agent:api-set-config"
  [[ "$1" == "$cmd" ]] && shift 1
  declare SERVICE="$1"
  declare CONFIG_PATH="$2"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a service name"
  [[ -z "$CONFIG_PATH" ]] && dokku_log_fail "Please specify path to agent.yaml"
  verify_service_name "$SERVICE"
  service_set_config "$SERVICE" "$CONFIG_PATH"
}

cmd-agent-api-set-config "$@"
