#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/common-functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

cmd-agent-api-create() {
  declare desc="create an Agent API service"
  local cmd="agent:api-create"
  [[ "$1" == "$cmd" ]] && shift 1
  declare SERVICE="$1"
  declare CONFIG_PATH="$2"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a service name"
  service_create "$SERVICE" "$CONFIG_PATH"
}

cmd-agent-api-create "$@"
