#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/common-functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

cmd-agent-api-unexpose() {
  declare desc="stop Agent API service (no longer exposed)"
  local cmd="agent:api-unexpose"
  [[ "$1" == "$cmd" ]] && shift 1
  declare SERVICE="$1"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a service name"
  verify_service_name "$SERVICE"
  service_unexpose "$SERVICE"
}

cmd-agent-api-unexpose "$@"
