#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/common-functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

cmd-agent-api-expose() {
  declare desc="expose Agent API service on a port"
  local cmd="agent:api-expose"
  [[ "$1" == "$cmd" ]] && shift 1
  declare SERVICE="$1"
  declare PORT="$2"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a service name"
  verify_service_name "$SERVICE"
  service_expose "$SERVICE" "$PORT"
}

cmd-agent-api-expose "$@"
